[window]
opacity = 0.9

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font]
size = 12.0

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[mouse]
hide_when_typing = true
